Get article by ID
LW95x/be-nc-news pull request #4
Opened 2023-11-20 16:47 UTC by LW95x

2023-11-20 16:59 UTC, popatre requested changes
Few bits to add to make this even better:

- [ ] https://notes.northcoders.com/courses/js-back-end/node-postgres#parameterized-queries

- [ ] Status 400: Bad request, invalid article_id
E.g. GET /api/articles/notanumber

- [ ] Status 404: Not found, article_id does not exist
E.g. GET /api/articles/9999

2023-11-20 16:59 UTC, popatre commented on __tests__/integration.test.js
> +      console.log(body.article)
remove console log

2023-11-20 16:59 UTC, popatre commented on __tests__/integration.test.js
> +          expect(typeof property.article_id).toBe("number");
You need to check the number is the one you've requested, in this case 1. 

At the moment you could get back any article and this would pass.

2023-11-20 16:59 UTC, popatre commented on __tests__/integration.test.js
> +})
We need some sad path tests for this

2023-11-20 16:59 UTC, popatre commented on db/controllers/getArticleById.controller.js
> +    })
Excellent controller

2023-11-20 16:59 UTC, popatre commented on db/models/getArticleById.model.js
> +    })
This leaves you open to sql injections. Look at parameterized queries

https://notes.northcoders.com/courses/js-back-end/node-postgres#parameterized-queries

2023-11-21 11:07 UTC, Hard-Luck approved these changes
Well done, really good changes 👍

2023-11-21 11:09 UTC, merged